# Generated by Django 4.1.4 on 2024-02-15 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonAvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('namaStaff', models.TextField()),
                ('idStaff', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('idTempat', models.AutoField(primary_key=True, serialize=False)),
                ('namaTempat', models.TextField(unique=True)),
                ('cajSewaan_hari_siang', models.CharField(max_length=100)),
                ('cajSewaan_jam_siang', models.CharField(max_length=100)),
                ('cajSewaan_hari_malam', models.CharField(max_length=100)),
                ('cajSewaan_jam_malam', models.CharField(max_length=100)),
                ('non_available_date', models.ManyToManyField(to='EventHub.nonavailabledate')),
            ],
        ),
        migrations.CreateModel(
            name='Tempahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noTempahan', models.IntegerField(blank=True, null=True, unique=True)),
                ('tarikhTempahan', models.DateField(auto_now_add=True)),
                ('selectedTime', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('jenisSewaan', models.CharField(choices=[('Per Hari', 'Sewaan Per Hari'), ('Per Jam', 'Sewaan Per Jam')], max_length=20)),
                ('slotSewaan', models.CharField(choices=[('Siang', 'Sewaan Slot Siang'), ('Malam', 'Sewaan Slot Malam')], max_length=10)),
                ('namaPenempah', models.TextField()),
                ('noKP', models.CharField(max_length=14)),
                ('noTelUtama', models.CharField(max_length=12)),
                ('alamat', models.TextField()),
                ('poskod', models.CharField(default='-', max_length=10)),
                ('negeri', models.TextField(default='-')),
                ('butiranBayaran', models.CharField(default='-', max_length=100)),
                ('namatempat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventHub.tempat')),
                ('selectedDate', models.ManyToManyField(to='EventHub.nonavailabledate')),
            ],
        ),
    ]
