# Generated by Django 4.1.4 on 2024-02-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0002_nonavailabletime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonavailabletime',
            name='time',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
