# Generated by Django 4.1.4 on 2024-02-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0003_alter_nonavailabletime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempat',
            name='non_available_times',
        ),
        migrations.AlterField(
            model_name='nonavailabledatetime',
            name='time',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='NonAvailableTime',
        ),
    ]
