# Generated by Django 4.1.4 on 2024-02-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0005_rename_non_available_dates_tempat_non_available_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempat',
            old_name='non_available_date',
            new_name='non_available_dates',
        ),
        migrations.RemoveField(
            model_name='tempahan',
            name='selectedTime',
        ),
        migrations.CreateModel(
            name='NonAvailableDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventHub.nonavailabledate')),
            ],
        ),
        migrations.AddField(
            model_name='tempat',
            name='non_available_date_times',
            field=models.ManyToManyField(to='EventHub.nonavailabledatetime'),
        ),
        migrations.AddField(
            model_name='tempahan',
            name='selectedTime',
            field=models.ManyToManyField(to='EventHub.nonavailabledatetime'),
        ),
    ]
