# Generated by Django 4.1.4 on 2024-02-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0007_rename_non_available_dates_tempat_non_available_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempahan',
            name='tarikhTempahan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
