# Generated by Django 4.1.4 on 2024-02-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0012_rename_non_available_dates_tempat_non_available_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tempat',
            old_name='non_available_date',
            new_name='non_available_dates',
        ),
        migrations.RemoveField(
            model_name='tempahan',
            name='selectedTime',
        ),
        migrations.AddField(
            model_name='tempat',
            name='non_available_times',
            field=models.ManyToManyField(to='EventHub.nonavailabletime'),
        ),
        migrations.AddField(
            model_name='tempahan',
            name='selectedTime',
            field=models.ManyToManyField(blank=True, to='EventHub.nonavailabletime'),
        ),
    ]
