# Generated by Django 4.1.4 on 2024-02-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0013_nonavailabletime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonavailabletime',
            name='time',
            field=models.CharField(default='-', max_length=100, unique=True),
        ),
    ]
